[project]
name = "booksapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.121.2",
    "psycopg[binary,pool]>=3.2.12",
    "uvicorn>=0.38.0",
]
